os: windows
language: python
python:
 - "3.8"
install:
 - pip install -r requirements.txt
script:
 - python Unittest.py
notifications:
   email:
     recipients:
       - jakeharold.pensavalle@gmail.com
     on_success: never
     on_failure: always
